/**
 * Optimized Icon Exports
 *
 * This file provides optimized exports for lucide-react icons to improve bundle size.
 * Only the icons actually used in the application are exported here.
 */

// Core navigation and layout icons
// Trading and finance specific icons
// Status and notification icons
// Action icons
export {
  Activity,
  Activity as ActivityIcon,
  AlertCircle as AlertIcon,
  AlertCircle,
  AlertTriangle,
  AlertTriangle as WarningIcon,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  BarChart3 as ChartIcon,
  Bot,
  Brain,
  Calendar,
  CheckCircle,
  CheckCircle as SuccessIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Coins,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  DollarSign as DollarIcon,
  Download as DownloadIcon,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  Filter,
  Gauge,
  GitBranch,
  Globe,
  Home,
  Info,
  Info as InfoIcon,
  Key,
  LayoutDashboard,
  LineChart,
  Loader2,
  Lock,
  LogOut,
  Menu,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Pause,
  PieChart,
  Play,
  Play as PlayIcon,
  Plus,
  RefreshCw,
  RotateCcw,
  RotateCcw as ResetIcon,
  Save,
  Search,
  Server,
  Settings,
  Shield,
  Square as StopIcon,
  Star,
  Target,
  Target as TargetIcon,
  TestTube,
  Trash2 as DeleteIcon,
  TrendingDown,
  TrendingDown as TrendingDownIcon,
  TrendingUp,
  TrendingUp as TrendingUpIcon,
  Upload,
  User,
  Users,
  Wifi,
  WifiOff,
  X,
  XCircle as ErrorIcon,
  Zap,
  Zap as ZapIcon,
} from "lucide-react";
